### ISSUE TITLE
Allow cross-feature tests in github actions

### ISSUE THREAD

**Issue by sdaveas** [axelarnetwork/tofnd#45]
We have github actions for testing only the regular build. Tests for `--feature="malicious"` need to be added.

The following options didn't work
```
- name: Run cargo test
   uses: actions-rs/cargo@v1
   with:
     command: test 
     args: --all-features
```
```
- name: Run cargo test
   uses: actions-rs/cargo@v1
   with:
     command: test --all-features
```
